server:
  port: 8981

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

llm:
  callRealLLM: ${CALL_REAL_LLM:true}
  llmUrl: ${LLM_URL:http://localhost:8080}
places:
  url: ${PLACES_URL:http://localhost:8980/graphql}