server:
  port: 8981

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

backend:
  graphql-url: ${PLACES_URL:http://localhost:8980/graphql}

llm:
  gpt-api-key: ${GPT_API_KEY:}
  gpt-organization-id: ${ORGANIZATION_ID:}
  gpt-project-id: ${PROJECT_ID:}